version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
before_build:
  - ps: $Env:PLATFORM_TOOLSET="v141"
build:
  project: PA193_test_parser_NEM.sln
  parallel: true
  verbosity: minimal
test:
  assemblies:
    - '.\*\tests.dll'
after_test:
  - vstest.console /logger:Appveyor Release\tests.dll
artifacts:
- path: $(configuration)\PA193_test_parser_NEM.exe
  name: Binary
deploy: off
