version: 1.0.{build}
configuration:
- Release
- Debug
build:
  project: PA193_test_parser_NEM.sln
  parallel: true
  verbosity: minimal
test:
  assemblies:
    - 'C:\projects\pa193-test-parser-nem\Release\tests.dll'
artifacts:
- path: $(configuration)\PA193_test_parser_NEM.exe
  name: Binary
deploy: off
